//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAHomeDelivery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class skus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skus()
        {
            this.detordenproductoshd = new HashSet<detordenproductoshd>();
        }
    
        public int id { get; set; }
        public string Sku { get; set; }
        public string Descripcion { get; set; }
        public string uom { get; set; }
        public string codigobarras { get; set; }
        public string codigobidimensional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detordenproductoshd> detordenproductoshd { get; set; }
    }
}
